### ISSUE TITLE
allowed items

### ISSUE THREAD

**Issue by dohomi** [simov/slugify#13]
Hi 

it would be great to allow some special chars. For example I would like to allow '/' and tried to extend slugify with:
```
slugify.extend({'/':'/'})
```
without success. Any idea how to solve this?

**Comment by simov** [comment]
You have to use the [`remove` option](https://github.com/simov/slugify#options) to specify the allowed special characters.

**Comment by lauhakari** [comment]
I tried to insert [$€£@] to the `remove`object but they still get translated into dollar, euro, pound etc. Is this really the expected behavior?

**Comment by simov** [comment]
@dohomi in your case you have to extend the default `remove` regexp `/[^\w\s$*_+~.()'"!\-:@]/g` to include `/`, note that the regexp is `[^...]` meaning that it will remove anything except the specified characters:

```js
slugify('/', {remove: /[^\w\s$*_+~.()'"!\-:@/]/g}) // I have added `/` here
// the result is '/'
```

@lauhakari in your case you have to override (or define) the character values, then you have to include those values in the `remove` regexp because `€£` falls outside of `\w` which is `A-Za-z0-9_`:

```js
slugify.extend({'$': '$', '€': '€', '£': '£', '@': '@'}) // override the characters
s('$€£@', {remove: /[^\w\s$*_+~.()'"!\-:@€£]/g}) // I have added `€£` here
// the result is: $€£@
```

**Comment by lauhakari** [comment]
Ahaaa. Thanx, I will try that out.
