### ISSUE TITLE
Doesn't normalize \u212B correctly

### ISSUE THREAD

**Issue by mesterjagels** [simov/slugify#81]
`slugify(\u212B)` outputs to å. This should be aa or a

**Comment by Trott** [comment]
For what it's worth, when I run `slugify('\u212B')`, I get an empty string, not å.

> This should be aa or a

Is it possible you mean to use `'\u00C5'` instead of `'\u212B'`? `'\u00C5'` would be the letter Å, and `slugify()` will convert that to "A". In contrast, `'\u212B'` is not actually a letter even though it looks like one. It is the symbol for angstroms (a unit of length).

**Comment by simov** [comment]
Thanks @Trott that seems correct.
