### ISSUE TITLE
How to make Identical post title to be unique by using slugify

### ISSUE THREAD

**Issue by akeren** [simov/slugify#83]
How can one handle or make identical post titles to uniquely identify by using slugify. This scenario is typical in a blog application.

**Comment by Trott** [comment]
I hope it's not bad form to point out another package in the issue tracker, but since this is a week old and you probably just want an answer to your problem: [slugger-unique](https://www.npmjs.com/package/slugger-unique) seems to do what you want. It does not have a lot of downloads/users, though, so you may want to take some extra care to make sure it's a high-quality package before using it. If no one else is using it and there are bugs lurking, you may be the first one to find all of them....

**Comment by Trott** [comment]
Oh, another package that has this functionality (just not by default--look for `counter()` in the documentation) is [@sindresorhus/slugify](https://www.npmjs.com/package/@sindresorhus/slugify) and it seems to have a good number of users.
